sudo: required
language: go
go:
  - stable
    
notifications:
  email:
    recipients:
      - chennqqi@qq.com # Current maintainer
    on_success: change
    on_failure: always

services:
  - docker
  
before_script:
  - sudo sysctl -w vm.max_map_count=262144

before_install:
  - docker run -d -p 4150:4150 -e "discovery.type=single-node" --name=nsqd nsqio/nsq /nsqd
  - docker logs nsqd
  - docker inspect nsqd
  - travis_wait 5

install:
  - go get -v ./...
  - travis_wait 5