language: go
go:
#  - "1.7"
#  - "1.8"
  - "1.13.x"
  - "1.14.x"
script: go test -race -coverprofile=coverage.txt -covermode=atomic github.com/chennqqi/nsqlogrus

after_success:
  - bash <(curl -s https://codecov.io/bash)
